Feature/header-refactorings
alexandrejuniorc/frontend-customer-portal pull request #3
Opened 2024-01-22 12:54 UTC by alexandrejuniorc

Implementa refatorações no css do header da aplicação.

2024-01-22 17:59 UTC, Cauaspinheiro reviewed
@alexandrejuniorc Vi aqui que tem bastante mudanças mexendo na ordem das classes do tailwind, tem um plugin do prettier que faz isso automaticamente.

https://tailwindcss.com/docs/editor-setup#automatic-class-sorting-with-prettier

2024-01-22 18:09 UTC, alexandrejuniorc commented
@Cauaspinheiro inclui a biblioteca que me indicou juntamente com o prettier, nesse último commit ele se trata apenas da configuraçõe do prettier e a extensão, no mais foram realizadas apenas formatações no código.

2024-01-22 18:15 UTC, Cauaspinheiro requested changes
@alexandrejuniorc Alguns pontos de atenção aqui:

- O scroll está sendo forçado na minha tela, mesmo ela tendo altura suficiente para mostrar todo o conteúdo da página, dentro do `Layout` você coloca o `Header` e depois uma div com `h-screen` forçando a página a ocupar mais de 100vh.
- Os outros pontos estão comentados dentro de cada arquivo

2024-01-22 18:15 UTC, Cauaspinheiro commented on src/components/template/header/logout.tsx
> +        className="flex gap-2 hover:bg-accent/10"
Aqui faltou um `items-center`, atualmente o botão está desalinhado. Acredito inclusive que podemos jogar esse `items-center` junto com o `flex gap-2 justify-center` direto no `Button`, forçando automaticamente esse behavior que você quer fazer em todos os botões.

2024-01-22 18:15 UTC, Cauaspinheiro commented on src/components/template/header/logout.tsx
>  export const Logout = () => {
Para deixar mais claro, acho que `LogoutButton` faz mais sentido.

2024-01-22 18:15 UTC, Cauaspinheiro commented on src/components/template/header/index.tsx
> +            <div className="relative">
Como essa div não tem `flex items-center` o ícone acaba desalinhado com o Input, dá para diminuir o tamanho máximo também ao meu ver, na minha tela de 1920 ficou extremamente largo (ver com a débora).

Se você colocar um `pointer-events-none` na estilização do `Search`, quando você clicar no ícone ele automaticamente dá o foco no Input

2024-01-22 18:23 UTC, Cauaspinheiro commented
> @Cauaspinheiro inclui a biblioteca que me indicou juntamente com o prettier, nesse último commit ele se trata apenas da configuraçõe do prettier e a extensão, no mais foram realizadas apenas formatações no código.

Boa! Aproveitando, adicionei a integração entre o Prettier e o ESLint. Acho que vale a pena você também adicionar as suas configurações que você acha melhor de styleguide dentro do .prettierrc

2024-01-23 14:05 UTC, danielbenicio approved these changes

2024-01-23 18:58 UTC, Cauaspinheiro approved these changes
LGTM! 🚀

2024-01-23 19:00 UTC, merged